<!--MANEJO DE ERRORES-->


<script>


try {
    console.log("en el try se agrega el codigo a evaluar");

    
} catch (error) {
    console.log("catch captura cualquier error surgido o lanzado en el try");
    
}finally {
    console.log("el bloque finally se ejecutara siempre al final de un bloque try catch");
}


try {
    let numero = "y"
    if(isNaN(numero)){
    throw new Error("el caracter introducido no es un numero")
    }
    console.log(numero * numero);
} catch (error) {

    console.log(`se produjo el siguiente error: ${error}`);
    
}

</script>